version: "2"
services:
  client:
    expose:
      - "5000"
      - "8080"
    ports:
      - "5000:5000"
      - "8080:8080"
    restart: always
    environment:
      ECHO_PORT: 5000
      HTTP_PORT: 8080
      GRPC_SERVER_HOST: server
      GRPC_SERVER_PORT: 8081
    image: zufardhiyaulhaq/echo-grpc-client
  server:
    expose:
      - "8081"
    ports:
      - "8081:8081"
    restart: always
    environment:
      GRPC_SERVER_PORT: 8081
    image: zufardhiyaulhaq/echo-grpc-server
