// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/streaming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingServer_ClientStream_FullMethodName        = "/com.gopay.echo.streaming.StreamingServer/ClientStream"
	StreamingServer_ServerStream_FullMethodName        = "/com.gopay.echo.streaming.StreamingServer/ServerStream"
	StreamingServer_BidirectionalStream_FullMethodName = "/com.gopay.echo.streaming.StreamingServer/BidirectionalStream"
)

// StreamingServerClient is the client API for StreamingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServerClient interface {
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamMessage, StreamResponse], error)
	ServerStream(ctx context.Context, in *StreamMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamResponse], error)
}

type streamingServerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServerClient(cc grpc.ClientConnInterface) StreamingServerClient {
	return &streamingServerClient{cc}
}

func (c *streamingServerClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamMessage, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingServer_ServiceDesc.Streams[0], StreamingServer_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_ClientStreamClient = grpc.ClientStreamingClient[StreamMessage, StreamResponse]

func (c *streamingServerClient) ServerStream(ctx context.Context, in *StreamMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingServer_ServiceDesc.Streams[1], StreamingServer_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_ServerStreamClient = grpc.ServerStreamingClient[StreamResponse]

func (c *streamingServerClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingServer_ServiceDesc.Streams[2], StreamingServer_BidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_BidirectionalStreamClient = grpc.BidiStreamingClient[StreamMessage, StreamResponse]

// StreamingServerServer is the server API for StreamingServer service.
// All implementations must embed UnimplementedStreamingServerServer
// for forward compatibility.
type StreamingServerServer interface {
	ClientStream(grpc.ClientStreamingServer[StreamMessage, StreamResponse]) error
	ServerStream(*StreamMessage, grpc.ServerStreamingServer[StreamResponse]) error
	BidirectionalStream(grpc.BidiStreamingServer[StreamMessage, StreamResponse]) error
	mustEmbedUnimplementedStreamingServerServer()
}

// UnimplementedStreamingServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServerServer struct{}

func (UnimplementedStreamingServerServer) ClientStream(grpc.ClientStreamingServer[StreamMessage, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedStreamingServerServer) ServerStream(*StreamMessage, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedStreamingServerServer) BidirectionalStream(grpc.BidiStreamingServer[StreamMessage, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedStreamingServerServer) mustEmbedUnimplementedStreamingServerServer() {}
func (UnimplementedStreamingServerServer) testEmbeddedByValue()                         {}

// UnsafeStreamingServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServerServer will
// result in compilation errors.
type UnsafeStreamingServerServer interface {
	mustEmbedUnimplementedStreamingServerServer()
}

func RegisterStreamingServerServer(s grpc.ServiceRegistrar, srv StreamingServerServer) {
	// If the following call panics, it indicates UnimplementedStreamingServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingServer_ServiceDesc, srv)
}

func _StreamingServer_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServerServer).ClientStream(&grpc.GenericServerStream[StreamMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_ClientStreamServer = grpc.ClientStreamingServer[StreamMessage, StreamResponse]

func _StreamingServer_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServerServer).ServerStream(m, &grpc.GenericServerStream[StreamMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_ServerStreamServer = grpc.ServerStreamingServer[StreamResponse]

func _StreamingServer_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServerServer).BidirectionalStream(&grpc.GenericServerStream[StreamMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingServer_BidirectionalStreamServer = grpc.BidiStreamingServer[StreamMessage, StreamResponse]

// StreamingServer_ServiceDesc is the grpc.ServiceDesc for StreamingServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.gopay.echo.streaming.StreamingServer",
	HandlerType: (*StreamingServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _StreamingServer_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStream",
			Handler:       _StreamingServer_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _StreamingServer_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/streaming.proto",
}
